Improve error message when there are different types
flamingo-run/drf-toolkit pull request #14
Opened 2021-12-29 13:53 UTC by lucassouto

When there are variables of different types, but with the same representation, the error message is confusing as the example below:

```
FAIL: test_update (v1.tests.tests_views.tests_patient_scheduling_views.PatientSchedulingViewTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lucassouto/nilo/hippocrates-api/hippocrates_api/v1/tests/tests_views/tests_patient_scheduling_views.py", line 238, in test_update
    self.assertResponseUpdated(expected_item=expected, response=response)
  File "/home/lucassouto/.cache/pypoetry/virtualenvs/hippocrates-api-k4F-OvWg-py3.9/lib/python3.9/site-packages/drf_kit/tests.py", line 69, in assertResponseUpdated
    self.assertResponse(
  File "/home/lucassouto/.cache/pypoetry/virtualenvs/hippocrates-api-k4F-OvWg-py3.9/lib/python3.9/site-packages/drf_kit/tests.py", line 103, in assertResponse
    self.assertResponseMatch(expected=expected_body, received=body)
  File "/home/lucassouto/.cache/pypoetry/virtualenvs/hippocrates-api-k4F-OvWg-py3.9/lib/python3.9/site-packages/drf_kit/tests.py", line 194, in assertResponseMatch
    raise AssertionError(msg)
AssertionError: There's 1 fields that differ
- updated_at: Received `2021-12-29T11:48:21Z`, but expected `2021-12-29T11:48:21Z`
```

This PR adds the variable's type as a prefix when they are of different types.

2021-12-29 14:46 UTC, elvisgs approved these changes

2021-12-29 16:27 UTC, elvisgs approved these changes

2021-12-29 16:54 UTC, lucasgomide reviewed
By following [conventional commits](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#type) I would use `refactor:`  prefix instead

2022-01-04 12:07 UTC, joaodaher requested changes
Do not commit those temp files generated by tests.

2022-01-04 12:21 UTC, lucassouto commented
@joaodaher, @lucasgomide asked to insert the files, I will remove them then

2022-01-04 13:31 UTC, joaodaher commented
It makes no sense adding files that tests will create every time.

2022-01-04 13:32 UTC, joaodaher commented on drf_kit/tests.py
> +                    msg = f"Received `{type(received_item)} - {received_item}`, but expected `{type(expected_item)} - {expected_item}`"  # pylint: disable=C0301
Split the line instead of suppressing the message.

2022-01-04 13:33 UTC, joaodaher commented on test_app/tests/tests_test_helpers.py
> +        message = "There's 1 fields that differ\n- age: Received `<class 'int'> - 13`, but expected `<class 'dict'> - {'amount': 13, 'min_age': 0}` "  # pylint: disable=C0301
Split the line instead of suppressing the message.

2022-01-04 13:33 UTC, joaodaher commented on test_app/tests/tests_test_helpers.py
> +        message = "There's 1 fields that differ\n- birthday: Received `<class 'str'> - 2022-01-01 00:00:00`, but expected `<class 'datetime.datetime'> - 2022-01-01 00:00:00` "  # pylint: disable=C030
Split the line instead of suppressing the message.

2022-01-04 19:40 UTC, joaodaher approved these changes
Great addition!
Thank you a lot!

2022-01-04 19:40 UTC, merged